### ISSUE TITLE
ifRouteIs in the server

### ISSUE THREAD

**Issue by marcelogarbin** [Arcesilas/active-state#10]
Hello, how are you?

I'm facing a problem, in my localhost the command `{{ Active::ifRouteIs('site.cardapio', 'pizzas']) }}` is working normally, but when I uploaded the project to a shared server it does not seem to work to function.

I use 2 methods in the menu, the "ifRouteIn" which is working normally and the "ifRouteIs" that is not, however the 2 work normal in localhost.

Do you have any suggestions whatsoever?

**Comment by Arcesilas** [comment]
Hi,

How is your route `site.cardapio` defined? What is the argument's name?
As you can see in the code, this check is performed like this:
```php
                $routeUri = route($r, $parameters, true);
                if ($this->request->fullUrlIs($routeUri)) {
                    return true;
                }
```
Normally, the route parameters are supposed to be an associative array: `[ parameter_name => parameter_value]`

In your check, you only use the value. Or...
```
{{ Active::ifRouteIs('site.cardapio', 'pizzas']) }}
```
is there a typo or is that your actual code? After `'pizzas` you close an array that is not open...

Also, if the problem persists, can you try to check the value of
```php
route($r, $parameters, true);
```
where `$r` is the route name, and the parameters the array as described above.

**Comment by marcelogarbin** [comment]
It was typo. It's inside an array.

I tried in this format too: `{{ Active::ifRouteIs('site.cardapio',['categoria' => 'pizzas']) }}`
Route: `Route::get('/cardapio/{categoria}', 'SiteController@cardapio')->name('site.cardapio');`

But the same thing happened, the active class is null.

Could it be some folder or file permission?

The website is https://www.fratellopizzaria.com.br

If you see, the "Início" menu is normal, with the active. However if you click on any of the items above, the class is not thrown.

**Comment by Arcesilas** [comment]
Forlders and file permissions are not involved in route url resolution.

Do you have the possibility to upload the project to a dedicated server of your own?

The only thing that comes to my mind is a problem with the Request. But that would be weird since the route resolution does work.

What method do you use for the 3 bottom items of the menu? (Inicio, ...)

You really need to check on the server what the results of `Request::fullUrl()` and `route('site.cardapio', ['categoria' => 'pizzas'], true)` are.
You may send an email or log to a file, in order to not display debug data on the website.

**Comment by marcelogarbin** [comment]
> Do you have the possibility to upload the project to a dedicated server of your own?

Actually I do not have any dedicated server at the moment, this is a free project. But if I can not, I can try to hire some.

> What method do you use for the 3 bottom items of the menu? (Inicio, ...)

Routes:
```php
Route::get('/', 'SiteController@index')->name('site.index');
Route::get('/contato', 'SiteController@contato')->name('site.contato');
Route::get('/localizacao', 'SiteController@localizacao')->name('site.localizacao');
```

View:
```html
<li class="menu-item {{ Active::ifRouteIn(['site.index']) }}"><a href="{{ url('/') }}">Início</a></li>
<li class="menu-item {{ Active::ifRouteIn(['site.localizacao']) }}"><a href="{{ route('site.localizacao') }}">Localização</a></li>
<li class="menu-item {{ Active::ifRouteIn(['site.contato']) }}"><a href="{{ route('site.contato') }}">Contato</a></li>
```


The result of the methods you say is what is shown on the screen?
https://www.fratellopizzaria.com.br/cardapio/pizzas
![image](https://user-images.githubusercontent.com/9335588/43475958-b0a5508a-94cd-11e8-9291-e9cebf008c1a.png)

I put the following on the view:
```html
<p style="font-size: 10px;">{{ Request::fullUrl() }}</p>
<p style="font-size: 10px;">{{ route('site.cardapio', ['categoria' => 'pizzas'], true) }}</p>
```

Is this what to do?

**Comment by marcelogarbin** [comment]
I have now tried with another method, and ran localhost and on server.

`{{ Active::ifUrlHas('cardapio/pizzas') }}`

the other items I left with the other method...

**Comment by Arcesilas** [comment]
As you can see, one has `http` and the other `https`
I think the problem is there.

**Comment by marcelogarbin** [comment]
It really seems that influenced that part. I set it to Full HTTPS and it's working.

This had been unappreciated by me, thank you for your help @Arcesilas !
