### ISSUE TITLE
Laravel 6 Support

### ISSUE THREAD

**Issue by marcelogarbin** [Arcesilas/active-state#12]
I tried to install on version 6.6, but to no avail.

**Comment by Arcesilas** [comment]
Yeah I know... I've thinking about it for quitesome time... Maybe I should stop to just think :)

**Comment by Arcesilas** [comment]
I'll work on it today. Because of time difference, you may have a new version when you wake up.

**Comment by Arcesilas** [comment]
Well... Actually, it requires a little more work. I could not have tests work correctly. I wanted to rewrite the tests to use Orchestra/TestBench and I had added some features in an unreleased v3...
I'm making all this square, since I'm a little lost in this package I haven't opened for months...

**Comment by marcelogarbin** [comment]
Hello, how are you? Thanks for your attention, I don't know if I can help you with anything, but any help you need just call me. I started a new project, and I'm about to use this package to keep a certain bootstrap [tab](https://getbootstrap.com/docs/4.3/components/navs/#tabs) open.

**Comment by Arcesilas** [comment]
One thing you could try... fork the repository, and change laravel version to `^6` in composer.json. Can you temporarily try/use this fork version and tell me if you meet any problem?
I'm currently just rewriting the tests with `orchestra/testbench`, which I could not run successfully anymore (for no reason, since I've always published 100% covered and successfully tested versions...). If all goes well by just changing the version of the dependency, then it  would mean working on the tests is enough.
Thank you!

**Comment by marcelogarbin** [comment]
Okay, that's fine with me.
Do you still use this package? If you are no longer interested in keeping this package, no problem, I can check to use localstorage to do this as you would like. I will try to check this issue of the update, about tests I have no experience about it, until I did not know this package you mentioned, I will try to inform me and study about. greetings

**Comment by Arcesilas** [comment]
I don't use this package because I have not been working on any project for a long time. I may need it anyway in a future project I'm late working on.

**Comment by Arcesilas** [comment]
Hope you're not to much in a hurry to have a L6 compatible version... I have not had as much time as I wanted and tomorrow I may have less time. But it's all going well for now, I have tests which did not pass anymore working with Orchestra/Testbench and L6.
Expect ActiveState v4 by the end of the week (yeah, v4: v3 was unreleased).

**Comment by marcelogarbin** [comment]
Okay, no problem for me, I'm out of time this month too. I have a project late to be delivered =/

**Comment by Arcesilas** [comment]
Would you have some time to have a look at https://github.com/Arcesilas/active-state/tree/develop-v4?

I'll wait for your feedback to release version 4 with Laravel 6 support.

**Comment by Arcesilas** [comment]
I finally released Version 4 which supports Laravel 6. Dropped Laravel 5 support.
