### ISSUE TITLE
ifQueryHas - Array to string conversion 

### ISSUE THREAD

**Issue by marcelogarbin** [Arcesilas/active-state#14]
Hello, how are you? I am trying to use the ifQueryHas method.
Laravel v5.5.48
active-state v2.1.0

I tried to follow this README example:
```
Check query string contains argument foo with value bar:
<a class="nav-link {{Active::ifQueryHas('videos.category', ['slug' => $category->slug])}}" href="{{ route('videos.category', $category->slug) }}">
```

Then returns me the following error:
![image](https://user-images.githubusercontent.com/9335588/71485704-36e80b80-27f1-11ea-824b-6bd01e1f1564.png)

my tag: ```<a class="nav-link {{Active::ifQueryHas('site.noticias.listar', ['pagina' => $noticias->currentPage()])}}" href="#">test</a>```

I'm trying to use the package with a pagination that involves categories and search. I don't know if I'm doing it the right way. If so, could you inform me? thanks

**Comment by marcelogarbin** [comment]
What I was trying to do initially was: 
```php
Active::ifRouteIs('site.noticias.listar', ['slug_categoria' => $categoria_atual ?? NULL, 'pagina' => ($noticias->currentPage() > 1)? $noticias->currentPage() : NULL, 'palavra' => $palavra ?? NULL])
```
the URL in question would be: ```http://domain.test/noticias```
with category: ```http://domain.test/noticias/geral```
with pagination: ```http://domain.test/noticias?page=2``` || ```http://domain.test/noticias/geral?page=2```
with search: ```http://domain.test/noticias/pesquisar?palavra=rerum``` || ```http://domain.test/noticias/pesquisar/geral?palavra=rerum``` || ```http://domain.test/noticias/pesquisar?palavra=rerum&page=2```

**Comment by marcelogarbin** [comment]
I was able to do what I wanted. I ended up using the "ifRouteIs" method.

noticias.blade.php
```blade
. . .
@section('categorias')
    @php
        $prts = ['slug_categoria' => NULL];
        if(request()->query('pagina'))
            $prts = $prts + ['pagina' => $noticias->currentPage()];
        if(isset($palavra))
            $prts = $prts + ['palavra' => $palavra];
    @endphp
    <h5 class="font-weight-bold pt-4">Categorias</h5>
    <ul class="nav nav-list flex-column mb-5">
        <li class="nav-item">
            <a href="{{ route('site.noticias.listar', $prts) }}" class="nav-link {{ Active::ifRouteIs('site.noticias.listar', $prts) }}"  title="Todas">Todas ({{ $total_noticias }})</a>
        </li>
        @foreach($categorias as $categoria)
            @php
                $prts = ['slug_categoria' => $categoria->slug];
                if(request()->query('pagina'))
                    $prts = $prts + ['pagina' => $noticias->currentPage()];
                if(isset($palavra))
                    $prts = $prts + ['palavra' => $palavra];
            @endphp
            <li class="nav-item">
                <a href="{{ route('site.noticias.listar', $prts) }}" class="nav-link {{ Active::ifRouteIs('site.noticias.listar', $prts) }}" title="{{ $categoria->nome }}">
                    {{ $categoria->nome }} ({{ $categoria->noticias_count ?? $categoria->noticias->count() }})
                </a>
            </li>
        @endforeach
    </ul>
@endsection
. . .
```

I know that for readability and performance  the correct thing is not to declare php code inside the view, but I used to shrink the code inside the tag "a".

![image](https://user-images.githubusercontent.com/9335588/71489301-b41c7c00-2803-11ea-9a2a-d67ec6e8be8b.png)

If you wish, you can close this issue.

**Comment by Arcesilas** [comment]
Hi!

Thanks for the report!

Could please post the complete error you got? You only pasted the lines where the exception is sent, not the actual message and log with arguments values...

I think there is a problem in the Readme, since checkQueryHas only takes one kind of arguments. The query is fixed, *de facto*, then the tests checks if the arguments can be found in the query. The example looks more like arguments for a route check, like `ifRouteHas().
I'll investigate when I have a little time.

**Comment by marcelogarbin** [comment]
that's the problem, maybe it's the documentation, I was trying to follow the readme model where there is the route and its parameters, but only the parameters are checked. That's what I noticed at least, I think the function itself is right.

**Comment by Arcesilas** [comment]
The last example in the Readme file was actually completely wrong. I don't event know what it was supposed to be...
[Documentation](https://github.com/Arcesilas/active-state/tree/develop-v4/docs) is certainly more reliable :)
