### ISSUE TITLE
CheckRoute

### ISSUE THREAD

**Issue by marcelogarbin** [Arcesilas/active-state#2]
Hello, 
I started using your package... 
the "Active::checkRoute()" method is working?

I did this test: `{{ Active::checkRoute('user.index') }}`

But returned: 
`ErrorException (E_ERROR)
Call to undefined method Arcesilas\ActiveState\Active::checkRoute() `

What can it be?

**Comment by Arcesilas** [comment]
It seems I have forgotten to change this method in Readme file :) Sorry...
The actual method is `Active::CheckRouteIs()`

I think I remember I changed `checkRoute()` to `checkRouteIs` for better consistency in the naming:
check + "what" + "how"
Therefore, checkRouteIs(), checkRouteIn(), checkUrlIs(), etc.

I need to update readme!

**Comment by marcelogarbin** [comment]
Perfect! No problem =)
