### ISSUE TITLE
[Question] Active::checkUrlHas()

### ISSUE THREAD

**Issue by marcelogarbin** [Arcesilas/active-state#3]
When I use the function if true would not it be to return the 'active_state' config?

**Comment by marcelogarbin** [comment]
Sorry, now I see:

> There are 2 kinds of tests: if* and check*.
> check* tests return a boolean, and can be used in any if loop
> if* tests return the active or inactive value. They simply translate the if* equivalent test into a string usable as a css class.

But even so there is a mistake for me.

E. I use: <li class="menu-item {{ Active::ifUrl('foo/bar') }}">Foo: Bar</li>

```
ErrorException (E_ERROR)
Call to undefined method Arcesilas\ActiveState\Active::ifUrl() 
```

**Comment by marcelogarbin** [comment]
I have already discovered, it is `Active::ifUrlHas()`

**Comment by Arcesilas** [comment]
Hi!
Thanks for your question and comments!
Do you think the readme file is not clear enough and should me more precise about the functions?
May be I should list all tests available rather than saying how to name them...?

**Comment by Arcesilas** [comment]
Also, you may consider having a look at the tests, which can be consider as part of the documentation:
https://github.com/Arcesilas/active-state/blob/develop/tests/Unit/IfTest.php

**Comment by marcelogarbin** [comment]
Hi! how are you?

I believe your Readme is fine. Maybe I failed to read the part where I said about the difference of methods, because my language is not English.

What may have happened in my case is also that the readme is outdated somewhere.
Ex.: https://github.com/Arcesilas/active-state#usage

If I use: `<li class="menu-item {{ Active::ifUrl('foo/bar') }}">Foo: Bar</li>`
Return:

> Call to undefined method Arcesilas\ActiveState\Active::ifUrl()

so i used(when viewing the source code of the class):  `<li class="menu-item {{ Active::ifUrlHas('foo/bar') }}">Foo: Bar</li>`

For there was no finding in the readme.

I think it's interesting the approach you've used in the Blade and Helpers section (You've listed all possible methods.).
Ex.: https://github.com/Arcesilas/active-state#blade-directives-1 and https://github.com/Arcesilas/active-state#helpers


You did a great job. 

Any other issues will bother you again. :sweat_smile:

**Comment by Arcesilas** [comment]
Thanks for your feedback! I really appreciate and it does not bother me!

I've changed some methods name during development and had already started writing the readme, while implementing methods at first. But I guess I forgot to update it while refactoring...

I may consider rewrite it (or at least go back over it).

I'm not english too, and I find it very interesting to see how many cultures can meet on platforms like Github! By the way, I've been learning Esperanto for 10 days now, and I will certainly consider translating documentation to Esperanto! If you are interested in translating the readme to you language, it would be appreciated too!

Anyway, I'm aware that the readme needs to be improved and I will certainly use the same approach as for Blade and Helpers section, as you mention: indeed, it's quite clear like this!

Thanks again!

**Comment by Arcesilas** [comment]
I've completely rewritten the documentation: it's now split into several files, which I consider easier to maintain and read.

And I've added an up-to-date [cheatsheet](https://github.com/Arcesilas/active-state/blob/develop/doc/cheatsheet.md)!

**Comment by marcelogarbin** [comment]
Very good! Congratulations.

I've been a bit busy these weeks, but I've put a reminder to translate your readme into pt-BR. I will share this package in the community/group of Laravel Brasil.

Thanks for your work.
