### ISSUE TITLE
Class 'Arcesilas\ActiveState\ActiveStateServiceProvider' not found

### ISSUE THREAD

**Issue by oranges13** [Arcesilas/active-state#4]
I am using version 1.2 with Laravel 5.4

I have installed according to the instructions and added

```
'providers' => [
    ...
    Arcesilas\ActiveState\ActiveStateServiceProvider::class,
]
```
to `config/app.php`

but I am receiving the error `Class 'Arcesilas\ActiveState\ActiveStateServiceProvider' not found`

**Comment by oranges13** [comment]
I believe this is due to the namespacing in the files of the 1.2 version:

`namespace Pyaesone17\ActiveState;`

**Comment by Arcesilas** [comment]
I guess you are not using the latest version, which is 1.2.1, in which namespaces have been fixed: https://github.com/Arcesilas/active-state/commit/dbd83409896b79ddbe481c6834cc178c86b048e7

**Comment by oranges13** [comment]
I used the version indicated in the readme for Laravel 5.4 (it only says
use version 1.2)

Perhaps the docs should specify that explicitly. Thanks.

**Comment by Arcesilas** [comment]
I supposed everyone always use `^` to specify the version, which would have lead to 1.2.1. I was wrong.

Doc fixed: https://github.com/Arcesilas/active-state/blob/develop/doc/installation.md#laravel-54-and-before
