### ISSUE TITLE
array in ifRouteIs not working

### ISSUE THREAD

**Issue by marcelogarbin** [Arcesilas/active-state#5]
Hello friend,
I'm using the package, however I realized that the "ifRouteIs" method is not working when used array.
Even though the route exists, validation is passed as if it does not exist.
I was even trying to make code changes, but I do not know how to cross-test in PHP.

**Comment by Arcesilas** [comment]
Hi ! 

Are you trying to do something like that:

```
$possibleRoutes = ['foo.one', 'foo.two'];
Active::ifRouteIs($possibleRoutes);
```
?

If so, this method is not intended to work with an array. You should use `Active::ifRouteIn` instead, it accepts a series of routes or an array as argument.
Or maybe I did not understand: in this case, could you provide an example of code you want to use?

**Comment by marcelogarbin** [comment]
Sorry, it was my fault.
I used "Active::ifRouteIn" and solved.

P.S.:

I have 2 routes, example:
```php
Route::get('/blog', 'SiteController@posts')->name('site.blog.posts');
Route::get('/blog/post/{slug_categoria}/{slug_noticia}', 'SiteController@post')->name('site.blog.post');
```

I can use this way to check both?
`class="{{ Active::ifRouteIn('site.blog.*') }}"`

**Comment by Arcesilas** [comment]
Actually, the code behind ifRouteIn is:
```
public function checkRouteIn(...$routes)
{
    return $this->request->routeIs(...$routes);
}
```

The `routeIs` method on Request calls `Route::named()` which uses `Str::is` to check the pattern.
As mentioned in [Laravel doc](https://laravel.com/docs/5.6/helpers#method-str-is), asterisks can be used as wildcards.

**Comment by marcelogarbin** [comment]
Perfect! Thanks for your return.

Good week. 

hug
